Repository UMC5-GrowUp/GrowUp_BackEnd, pull requests merged in 2024-01, with the labels that each got.

#3 CI/CD
  .ebextensions_dev/00.makefiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  .platform/nginx/conf.d/client_max_body_size.conf
  Procfile
  build.gradle
Labels: :sparkles: feat, ci

#19 [FEAT] 화면 공유 기능 구현
  build.gradle
  src/main/java/Growup/spring/media/config/KurentoConfig.java
  src/main/java/Growup/spring/media/handler/CallHandler.java
  src/main/java/Growup/spring/media/rooms/Room.java
  src/main/java/Growup/spring/media/rooms/RoomManager.java
  src/main/java/Growup/spring/media/users/UserSession.java
Labels: :sparkles: feat

#39 Fix/38
  .platform/nginx.conf
Labels: :bug: fix

#41 [FIX] CORS,오타 수정
  src/main/java/Growup/spring/User/Controller/UserController.java
  src/main/java/Growup/spring/User/service/UserService.java
  src/main/java/Growup/spring/User/service/UserServiceImpl.java
  src/main/java/Growup/spring/security/SecurityConfig.java
Labels: :bug: fix

#42 [FIX] CORS,오타 수정
  src/main/java/Growup/spring/security/SecurityConfig.java
Labels: :bug: fix

#43 [FIX] 🐛 WebSocket 연결 오류 수정
  .platform/nginx.conf
Labels: :bug: fix

#45 [FIX] 오타수정, cors 비활성화 제거
  src/main/java/Growup/spring/constant/status/ErrorStatus.java
  src/main/java/Growup/spring/domain/Liked.java
  src/main/java/Growup/spring/domain/Participate.java
  src/main/java/Growup/spring/growRoom/domain/GrowRoom.java
  src/main/java/Growup/spring/growRoom/domain/Pin.java
  src/main/java/Growup/spring/growRoom/domain/PinComment.java
  src/main/java/Growup/spring/growRoom/dto/AddGrowRoomRequest.java
  src/main/java/Growup/spring/security/CustomUserDetail.java
  src/main/java/Growup/spring/security/JpaUserDetailsService.java
  src/main/java/Growup/spring/security/SecurityConfig.java
  src/main/java/Growup/spring/user/controller/UserController.java
  src/main/java/Growup/spring/user/converter/UserConverter.java
  src/main/java/Growup/spring/user/dto/RefreshTokenRes.java
  src/main/java/Growup/spring/user/dto/UserDtoReq.java
  src/main/java/Growup/spring/user/dto/UserDtoRes.java
  src/main/java/Growup/spring/user/model/Enum/UserRole.java
  src/main/java/Growup/spring/user/model/Enum/UserState.java
  src/main/java/Growup/spring/user/model/Prefer.java
  src/main/java/Growup/spring/user/model/User.java
  src/main/java/Growup/spring/user/model/UserPrefer.java
  src/main/java/Growup/spring/user/repository/UserRepository.java
  src/main/java/Growup/spring/user/service/UserService.java
  src/main/java/Growup/spring/user/service/UserServiceImpl.java
Labels: :bug: fix

#47 오타수정
  src/main/java/Growup/spring/user/service/UserServiceImpl.java
Labels: :bug: fix

#48 오타 수정
  src/main/java/Growup/spring/user/service/UserServiceImpl.java
Labels: :bug: fix

#50 수정
  src/main/resources/application.yml
Labels: :bug: fix

#52 수정
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  src/main/java/Growup/spring/test.java
Labels: :bug: fix

#63 [FEAT] ✨ 투두리스트 조회,등록 API 구현
  src/main/java/Growup/spring/domain/Liked.java
  src/main/java/Growup/spring/domain/Participate.java
  src/main/java/Growup/spring/domain/ParticipateTime.java
  src/main/java/Growup/spring/todoList/controller/TodoListController.java
  src/main/java/Growup/spring/todoList/dto/TodoDtoListReq.java
  src/main/java/Growup/spring/todoList/service/TodoListImpl.java
  src/main/java/Growup/spring/user/controller/UserController.java
  src/main/java/Growup/spring/user/dto/UserDtoReq.java
  src/main/java/Growup/spring/user/model/User.java
  src/main/java/Growup/spring/user/repository/UserRepository.java
Labels: :sparkles: feat

#65 [FEAT] 투두리스트 url 수정 ✨
  src/main/java/Growup/spring/todoList/controller/TodoListController.java
Labels: :sparkles: feat

#72 수정
  src/main/java/Growup/spring/domain/Liked.java
  src/main/java/Growup/spring/domain/Participate.java
  src/main/java/Growup/spring/domain/ParticipateTime.java
  src/main/java/Growup/spring/user/model/User.java
Labels: :bug: fix

#73 cors 수정
  .platform/nginx/nginx.conf
  src/main/java/Growup/spring/security/SecurityConfig.java
Labels: :bug: fix

#74 수정
  src/main/java/Growup/spring/security/SecurityConfig.java
Labels: :bug: fix

#75 수정
  .platform/nginx/nginx.conf
  src/main/java/Growup/spring/security/SecurityConfig.java
Labels: :bug: fix
