Repository UMC5-GrowUp/GrowUp_BackEnd, pull requests merged in 2024-02, with the labels that each got.

#80 [FEAT]투두리스트 내용 수정 API 구현
  src/main/java/Growup/spring/todoList/controller/TodoListController.java
  src/main/java/Growup/spring/todoList/converter/TodoListConverter.java
  src/main/java/Growup/spring/todoList/dto/TodoDtoListReq.java
  src/main/java/Growup/spring/todoList/dto/TodoDtoListRes.java
  src/main/java/Growup/spring/todoList/service/TodoListImpl.java
  src/main/java/Growup/spring/todoList/service/TodoListService.java
Labels: :sparkles: feat

#86 [FIX] 인증 url 수정 🎉
  src/main/java/Growup/spring/email/service/EmailService.java
Labels: :bug: fix

#87 [FEAT] liveRoom Paging기능 추가
  src/main/java/Growup/spring/participate/controller/ParticipateController.java
  src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
  src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
  src/main/java/Growup/spring/participate/model/Participate.java
  src/main/java/Growup/spring/participate/repository/ParticipateRepository.java
  src/main/java/Growup/spring/participate/service/ParticipateService.java
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :sparkles: feat

#91 fix(build.gradle): kurento 최신 버전으로 수정
  build.gradle
Labels: :bug: fix

#92 [FEAT] 캘린더 해당 날짜- 할일 등록 API 작성 🎉
  src/main/java/Growup/spring/calender/controller/CalenderController.java
  src/main/java/Growup/spring/calender/converter/CalenderConverter.java
  src/main/java/Growup/spring/calender/dto/CalenderDtoReq.java
  src/main/java/Growup/spring/calender/dto/CalenderRes.java
  src/main/java/Growup/spring/calender/model/Calender.java
  src/main/java/Growup/spring/calender/model/Enum/CalenderColor.java
  src/main/java/Growup/spring/calender/model/Enum/CalenderStatus.java
  src/main/java/Growup/spring/calender/repository/CalenderRepository.java
  src/main/java/Growup/spring/calender/service/CalenderService.java
  src/main/java/Growup/spring/calender/service/CalenderServiceimpl.java
  src/main/java/Growup/spring/user/model/User.java
Labels: :sparkles: feat

#95 [FEAT] 캘린더 조회,삭제,수정 API 작성 🎉
  src/main/java/Growup/spring/calender/controller/CalenderController.java
  src/main/java/Growup/spring/calender/converter/CalenderConverter.java
  src/main/java/Growup/spring/calender/dto/CalenderDtoReq.java
  src/main/java/Growup/spring/calender/dto/CalenderDtoRes.java
  src/main/java/Growup/spring/calender/dto/CalenderRes.java
  src/main/java/Growup/spring/calender/model/Calender.java
  src/main/java/Growup/spring/calender/repository/CalenderRepository.java
  src/main/java/Growup/spring/calender/service/CalenderService.java
  src/main/java/Growup/spring/calender/service/CalenderServiceimpl.java
  src/main/java/Growup/spring/constant/handler/CalenderHandler.java
  src/main/java/Growup/spring/constant/status/ErrorStatus.java
  src/main/java/Growup/spring/security/JwtAuthenticationFilter.java
  src/main/java/Growup/spring/todoList/service/TodoListService.java
Labels: :sparkles: feat

#96 배포 확인
  src/main/resources/application.yml
Labels: :bug: fix

#97 배포 확인
  src/main/resources/application.yml
Labels: :bug: fix

#101 배포 확인
  src/main/java/Growup/spring/security/SecurityConfig.java
Labels: :bug: fix

#102 배포 확인
  src/main/java/Growup/spring/security/SecurityConfig.java
Labels: :bug: fix

#104 배포 확인
  .github/workflows/dev_deploy.yml
Labels: :bug: fix

#105 배포 확인
  .github/workflows/dev_deploy.yml
Labels: :bug: fix

#106 배포 확인
  .github/workflows/dev_deploy.yml
Labels: :bug: fix

#107 배포 확인
  .github/workflows/dev_deploy.yml
Labels: :bug: fix

#108 PIN
  src/main/java/Growup/spring/constant/status/ErrorStatus.java
  src/main/java/Growup/spring/growRoom/controller/GrowRoomController.java
  src/main/java/Growup/spring/growRoom/controller/PinController.java
  src/main/java/Growup/spring/growRoom/converter/PinConverter.java
  src/main/java/Growup/spring/growRoom/dto/GrowRoomDtoRes.java
  src/main/java/Growup/spring/growRoom/dto/PinDtoReq.java
  src/main/java/Growup/spring/growRoom/dto/PinDtoRes.java
  src/main/java/Growup/spring/growRoom/model/Pin.java
  src/main/java/Growup/spring/growRoom/repository/PinRepository.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
  src/main/java/Growup/spring/growRoom/service/PinService.java
  src/main/java/Growup/spring/growRoom/service/PinServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#112 GrowRoom 모집기간 추가
  src/main/java/Growup/spring/growRoom/converter/RecruitmentPeriodConverter.java
  src/main/java/Growup/spring/growRoom/dto/GrowRoomDtoReq.java
  src/main/java/Growup/spring/growRoom/dto/GrowRoomDtoRes.java
  src/main/java/Growup/spring/growRoom/model/GrowRoom.java
  src/main/java/Growup/spring/growRoom/model/Post.java
  src/main/java/Growup/spring/growRoom/model/component/RecruitmentPeriod.java
  src/main/java/Growup/spring/growRoom/repository/RecruitmentPeriodRepository.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#114 [FEAT]유저 관련 에러 수정
  src/main/java/Growup/spring/constant/exeption/ExceptionAdvice.java
  src/main/java/Growup/spring/user/controller/UserController.java
  src/main/java/Growup/spring/user/dto/UserDtoReq.java
  src/main/java/Growup/spring/user/service/UserService.java
  src/main/java/Growup/spring/user/service/UserServiceImpl.java
Labels: :bug: fix

#115 [FEAT] 에러 수정
  src/main/java/Growup/spring/constant/ApiResponse.java
  src/main/java/Growup/spring/constant/status/ErrorStatus.java
Labels: :bug: fix

#116 [FIX] 사용중인 닉네임 HttpStatus.BAD_REQUEST -> HttpStatus.OK 로 개발단계에선 수정
  src/main/java/Growup/spring/constant/status/ErrorStatus.java
Labels: :bug: fix

#118 에러 코드 수정
  src/main/java/Growup/spring/constant/ApiResponse.java
  src/main/java/Growup/spring/constant/exeption/ExceptionAdvice.java
Labels: :bug: fix

#124 기능 추가
  src/main/java/Growup/spring/constant/status/ErrorStatus.java
  src/main/java/Growup/spring/growRoom/controller/GrowRoomController.java
  src/main/java/Growup/spring/growRoom/model/GrowRoom.java
  src/main/java/Growup/spring/growRoom/model/Pin.java
  src/main/java/Growup/spring/growRoom/model/PinComment.java
  src/main/java/Growup/spring/growRoom/repository/GrowRoomRepository.java
  src/main/java/Growup/spring/growRoom/repository/PinCommentRepository.java
  src/main/java/Growup/spring/growRoom/repository/PinRepository.java
  src/main/java/Growup/spring/growRoom/service/CleanupTask.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomService.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
  src/main/java/Growup/spring/growRoom/service/PinCommentServiceImpl.java
  src/main/java/Growup/spring/growRoom/service/PinServiceImpl.java
Labels: :sparkles: feat

#126 Fix/125
  src/main/java/Growup/spring/growRoom/controller/GrowRoomController.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
  src/main/java/Growup/spring/liked/controller/LikedController.java
  src/main/java/Growup/spring/liked/converter/LikedConverter.java
  src/main/java/Growup/spring/liked/dto/LikedDtoRes.java
  src/main/java/Growup/spring/liked/repository/LikedRepository.java
  src/main/java/Growup/spring/liked/service/LikedService.java
  src/main/java/Growup/spring/liked/service/LikedServiceImpl.java
Labels: :bug: fix

#127 code 정리
  src/main/java/Growup/spring/liked/service/LikedServiceImpl.java
Labels: :recycle: refactor

#128 Liked 오류 수정(객체생성)
  src/main/java/Growup/spring/growRoom/controller/GrowRoomController.java
  src/main/java/Growup/spring/growRoom/dto/GrowRoomDtoRes.java
  src/main/java/Growup/spring/liked/controller/LikedController.java
  src/main/java/Growup/spring/liked/converter/LikedConverter.java
  src/main/java/Growup/spring/liked/repository/LikedRepository.java
  src/main/java/Growup/spring/liked/service/LikedServiceImpl.java
  src/main/java/Growup/spring/security/JwtProvider.java
Labels: :bug: fix

#129 [Feat] 라이브룸 입장,퇴장 api 구현/ [Fix] 캘린더,투두리스트 작성자 작성
  src/main/java/Growup/spring/calender/controller/CalenderController.java
  src/main/java/Growup/spring/constant/status/ErrorStatus.java
  src/main/java/Growup/spring/participate/controller/ParticipateController.java
  src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
  src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
  src/main/java/Growup/spring/participate/model/Participate.java
  src/main/java/Growup/spring/participate/model/ParticipateTime.java
  src/main/java/Growup/spring/participate/repository/ParticipateRepository.java
  src/main/java/Growup/spring/participate/repository/ParticipateTimeRepository.java
  src/main/java/Growup/spring/participate/service/ParticipateService.java
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
  src/main/java/Growup/spring/todoList/controller/TodoListController.java
Labels: :bug: fix, :sparkles: feat

#130 Feat/121
  src/main/java/Growup/spring/constant/status/ErrorStatus.java
  src/main/java/Growup/spring/growRoom/controller/GrowRoomController.java
  src/main/java/Growup/spring/growRoom/repository/GrowRoomRepository.java
  src/main/java/Growup/spring/growRoom/repository/PeriodRepository.java
  src/main/java/Growup/spring/growRoom/repository/PostRepository.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomService.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
  src/main/java/Growup/spring/liked/service/LikedService.java
  src/main/java/Growup/spring/liked/service/LikedServiceImpl.java
Labels: :sparkles: feat

#132 growroom 전체조회 주소 수정
  src/main/java/Growup/spring/growRoom/controller/GrowRoomController.java
  src/main/java/Growup/spring/security/JwtProvider.java
Labels: :bug: fix

#133 Feat/131
  src/main/java/Growup/spring/growRoom/controller/GrowRoomController.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomService.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
Labels: :sparkles: feat

#134 Feat/131
  src/main/java/Growup/spring/constant/status/ErrorStatus.java
  src/main/java/Growup/spring/growRoom/controller/GrowRoomController.java
  src/main/java/Growup/spring/growRoom/repository/GrowRoomRepository.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
  src/main/java/Growup/spring/participate/controller/ParticipateController.java
  src/main/java/Growup/spring/participate/repository/ParticipateRepository.java
Labels: :sparkles: feat

#135 🔧 그로우룸{id} 조회 반환값 수정
  src/main/java/Growup/spring/growRoom/dto/GrowRoomDtoRes.java
Labels: :wrench: retouch

#137 [FIX] cors 웹배포 도메인 추가
  src/main/java/Growup/spring/security/SecurityConfig.java
Labels: :bug: fix

#138 [FIX] cors 웹배포 도메인 (이메일 인증) 수정
  src/main/java/Growup/spring/email/service/EmailService.java
Labels: :bug: fix

#141 Retouch/136
  src/main/java/Growup/spring/growRoom/controller/GrowRoomController.java
  src/main/java/Growup/spring/growRoom/controller/PinController.java
  src/main/java/Growup/spring/growRoom/dto/PinDtoRes.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomService.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
  src/main/java/Growup/spring/liked/service/LikedServiceImpl.java
  src/main/java/Growup/spring/security/SecurityConfig.java
Labels: :sparkles: feat

#142 Retouch/136
  src/main/java/Growup/spring/growRoom/dto/GrowRoomDtoRes.java
  src/main/java/Growup/spring/security/SecurityConfig.java
Labels: :bug: fix

#143 Fix/85 login 403 수정
  src/main/java/Growup/spring/security/SecurityConfig.java
Labels: :bug: fix

#144 [FIX]jwt 개발단계 시간 수정
  src/main/java/Growup/spring/security/JwtProvider.java
Labels: :bug: fix

#145 Retouch/136
  src/main/java/Growup/spring/growRoom/controller/PinCommentController.java
  src/main/java/Growup/spring/growRoom/controller/PinController.java
  src/main/java/Growup/spring/growRoom/converter/PinCommentConverter.java
  src/main/java/Growup/spring/growRoom/converter/PinConverter.java
  src/main/java/Growup/spring/growRoom/dto/PinDtoRes.java
  src/main/java/Growup/spring/growRoom/repository/GrowRoomRepository.java
  src/main/java/Growup/spring/growRoom/repository/PeriodRepository.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomService.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
  src/main/java/Growup/spring/growRoom/service/PinCommentService.java
  src/main/java/Growup/spring/growRoom/service/PinCommentServiceImpl.java
  src/main/java/Growup/spring/growRoom/service/PinService.java
  src/main/java/Growup/spring/growRoom/service/PinServiceImpl.java
Labels: :wrench: retouch

#147 [FIX] 파일 업로드 크기 수정
  src/main/resources/application.yml
Labels: :bug: fix

#148 Retouch/136
  src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
Labels: :wrench: retouch

#149 ParticipateController
  src/main/java/Growup/spring/growRoom/service/GrowRoomService.java
  src/main/java/Growup/spring/participate/controller/ParticipateController.java
  src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
  src/main/java/Growup/spring/participate/repository/ParticipateRepository.java
  src/main/java/Growup/spring/participate/service/ParticipateService.java
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :sparkles: feat

#150 [FIX] 그로우룸 참여자(시간) 관련 api 구현완료
  src/main/java/Growup/spring/GrowupApplication.java
  src/main/java/Growup/spring/constant/status/ErrorStatus.java
  src/main/java/Growup/spring/liked/service/LikedServiceImpl.java
  src/main/java/Growup/spring/participate/controller/ParticipateController.java
  src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
  src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
  src/main/java/Growup/spring/participate/model/ParticipateTime.java
  src/main/java/Growup/spring/participate/repository/ParticipateRepository.java
  src/main/java/Growup/spring/participate/service/ParticipateService.java
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
  src/main/java/Growup/spring/user/service/UserServiceImpl.java
Labels: :sparkles: feat

#152 수정 및 기능 추가
  src/main/java/Growup/spring/growRoom/controller/PinCommentController.java
  src/main/java/Growup/spring/growRoom/controller/PinController.java
  src/main/java/Growup/spring/growRoom/service/CleanupTask.java
  src/main/java/Growup/spring/growRoom/service/GrowRoomCategoryServiceImpl.java
  src/main/java/Growup/spring/growRoom/service/PinCommentService.java
  src/main/java/Growup/spring/growRoom/service/PinCommentServiceImpl.java
  src/main/java/Growup/spring/growRoom/service/PinService.java
  src/main/java/Growup/spring/growRoom/service/PinServiceImpl.java
Labels: :sparkles: feat, :wrench: retouch

#153 기능 수정
  src/main/java/Growup/spring/constant/status/ErrorStatus.java
  src/main/java/Growup/spring/growRoom/service/CleanupTask.java
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :wrench: retouch

#154 오탈자 수정
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :bug: fix

#155 [FEAT]참여자 관련 코드 수정
  src/main/java/Growup/spring/growRoom/service/CleanupTask.java
  src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
  src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :bug: fix, :sparkles: feat

#156 [FIX] 그로우룸 참여시 에러 수정
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :bug: fix, :sparkles: feat

#157 PinComment 생성 오류
  src/main/java/Growup/spring/growRoom/service/PinCommentServiceImpl.java
Labels: :bug: fix

#158 cors url 수정
  src/main/java/Growup/spring/security/SecurityConfig.java
Labels: :bug: fix

#159 participateId 응답으로 수정
  src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
  src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
Labels: :bug: fix, :sparkles: feat

#160 [FIX]participateId 응답으로 수정
  src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
Labels: :bug: fix

#161 [FIX}랭킹별 누적시간(주간/월간/일간) 조회시 수정
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :bug: fix

#162 [FIX] 라이브룸 입장 퇴장시 방장이 입장할때 시간 증가 x/퇴장시 수정
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :bug: fix, :sparkles: feat

#164 [FEAT] 라이브룸 api 최종구현
  src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
  src/main/java/Growup/spring/participate/controller/ParticipateController.java
  src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
  src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
  src/main/java/Growup/spring/participate/model/Enum/ParticipateStatus.java
  src/main/java/Growup/spring/participate/model/Participate.java
  src/main/java/Growup/spring/participate/repository/ParticipateRepository.java
  src/main/java/Growup/spring/participate/repository/ParticipateTimeRepository.java
  src/main/java/Growup/spring/participate/service/ParticipateService.java
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :bug: fix, :sparkles: feat

#165 [FIX] 라이브룸 타이머클릭시 api 수정
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :bug: fix

#166 [FIX] 라이브룸 타이머클릭시 api 수정
  src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :bug: fix

#169 [FIX] participate 수정
  src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :bug: fix

#170 [FIX] participate enter 수정 && jwt 시간 수정
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
  src/main/java/Growup/spring/security/JwtProvider.java
Labels: :bug: fix

#171 [FIX] participate enter 수정
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :bug: fix

#172 [FIX] participate enter 수정
  src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
Labels: :bug: fix

#173 [FIX] participate enter 수정
  src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
Labels: :bug: fix
